export enum Difficulty {
    EASY = 'Dễ',
    MEDIUM = 'Trung bình',
    HARD = 'Khó',
}

export interface QuestionOption {
    id: string; // 'A', 'B', 'C', ...
    label: string; // 'A.', 'B.', ...
    value: string;
    isCorrect: boolean;
}

export interface QuestionData {
    // Note: 'id' is typically generated by the database, so it's optional on creation
    id?: string;
    grade: string;
    topic: string;
    difficulty: Difficulty;
    tags: string[];
    content: string;
    options: QuestionOption[];
    solution: string;
    notes: string;
    imageUrl?: string | null;
}

// This interface represents the raw response from the Gemini API
// which will be forwarded by our backend.
export interface GeminiOption {
    value: string;
    isCorrect: boolean;
}

export type GeminiResponse = Partial<Omit<QuestionData, 'options' | 'difficulty' | 'id'>> & {
    options?: GeminiOption[];
    difficulty?: string; // Gemini might return 'T.Bình' which we map to MEDIUM
    imageUrl?: string; // AI can also return an image URL
};
